name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image with latest stable Nvidia base image together with .NET Core and OpenCvSharp 
      run: |
        docker build . --file ./BuildImageNvidiaCuda/Dockerfile --tag dockeratso/nvidia-dotnet-core-sdk-opencvsharp:latest

